# ===== DataSource =====
spring.datasource.url=jdbc:mysql://localhost:3306/forum_enicarthage?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===== Log4j2 =====
logging.config=classpath:log4j2.xml

# ===== JWT =====
app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
app.jwt.expiration=86400000

# ===== Multipart (upload CV) =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===== Scheduling =====
spring.task.scheduling.enabled=true

# ===== Microservice analyse CV (Python FastAPI) =====
app.cv-ai.enabled=true
app.cv-ai.base-url=http://127.0.0.1:8000

server.port=8081

spring.jackson.serialization.write-dates-as-timestamps=false



# ===== Mail =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fatmabouajla3@gmail.com
spring.mail.password=spifcfsgvfbhprmt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.url=http://localhost:4200